name: release

on:
  push:
    tags:
      - '*'

env:
  PYTHON_VERSION: '3.9'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dependencies
        run: pip install --target .python_packages/lib/site-packages/ -r requirements.txt

      - name: make artifact
        run: zip -r artifact.zip . -x ".git/*" ".github/*" ".gitignore"

      - name: Draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            --draft \
            --verify-tag \
            "./artifact.zip#artifact.zip"
